# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Atlan < Formula
  desc "Atlan CLI"
  homepage "https://developer.atlan.com/sdks/cli"
  version "0.1.6"
  license "Apache-2.0"

  on_macos do
    on_intel do
      url "https://github.com/atlanhq/atlan-cli-releases/releases/download/v0.1.6/atlan_Darwin_amd64.tar.gz"
      sha256 "fdbf6306a4303aa5aa52a70013f1be273a3a3bf8f7ec57027ed207500e2022ef"

      def install
        bin.install "atlan"
      end
    end
    on_arm do
      url "https://github.com/atlanhq/atlan-cli-releases/releases/download/v0.1.6/atlan_Darwin_arm64.tar.gz"
      sha256 "bd4eeb8356bd8fff044ae19d89391cb8bab26af7e0c515749b933231836fad75"

      def install
        bin.install "atlan"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/atlanhq/atlan-cli-releases/releases/download/v0.1.6/atlan_Linux_amd64.tar.gz"
        sha256 "b14bc818c4e153271422899fa994029d2f584732d288673287a4af2cfa8ec860"

        def install
          bin.install "atlan"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/atlanhq/atlan-cli-releases/releases/download/v0.1.6/atlan_Linux_arm64.tar.gz"
        sha256 "65ba750ce39fb89393ee1e0a8212f2a4dbf27faf54488e72d3b504856e516d1c"

        def install
          bin.install "atlan"
        end
      end
    end
  end

  def post_install
    system "#{bin}/atlan"
  end
end
