# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Atlan < Formula
  desc "Atlan CLI"
  homepage "https://developer.atlan.com/sdks/cli"
  version "0.1.12"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/atlanhq/atlan-cli-releases/releases/download/v0.1.12/atlan_Darwin_amd64.tar.gz"
      sha256 "941316459401855de1cb7f9c5f51dd4def904e2f1ea3cd57392e60d38a2a5530"

      define_method(:install) do
        bin.install "atlan"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/atlanhq/atlan-cli-releases/releases/download/v0.1.12/atlan_Darwin_arm64.tar.gz"
      sha256 "d7316fb1e53da6a9d131b340f1ccda1495a59111b897450ad623491448d43b60"

      define_method(:install) do
        bin.install "atlan"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/atlanhq/atlan-cli-releases/releases/download/v0.1.12/atlan_Linux_amd64.tar.gz"
      sha256 "d4961f89457e83532e7caeae0bc700d4488dba9f79c3f6afc5b399dddcb4d576"
      define_method(:install) do
        bin.install "atlan"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/atlanhq/atlan-cli-releases/releases/download/v0.1.12/atlan_Linux_arm64.tar.gz"
      sha256 "7842c53fbb35f0b977316f0d0f6cb796f789a42eb076babd2737d17e4c8dd538"
      define_method(:install) do
        bin.install "atlan"
      end
    end
  end

  def post_install
    system "#{bin}/atlan"
  end
end
