# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class AtlanAT013 < Formula
  desc "Atlan CLI"
  homepage "https://developer.atlan.com/sdks/cli"
  version "0.1.3-alpha"
  license "Apache-2.0"

  on_macos do
    on_intel do
      url "https://github.com/atlanhq/atlan-cli-releases/releases/download/0.1.3-alpha/atlan_Darwin_amd64.tar.gz"
      sha256 "8a56d24f5d897c050f0796580ddc327df21776a004784e8223c8869217f04c4f"

      def install
        bin.install "atlan"
      end
    end
    on_arm do
      url "https://github.com/atlanhq/atlan-cli-releases/releases/download/0.1.3-alpha/atlan_Darwin_arm64.tar.gz"
      sha256 "981e0fecb4d60db7ba0c72cffd01ec833fe69b579d6eb2480da9325b672d55f9"

      def install
        bin.install "atlan"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/atlanhq/atlan-cli-releases/releases/download/0.1.3-alpha/atlan_Linux_amd64.tar.gz"
        sha256 "6c3742a17741ff92197d9bab5a88d4a58f20ef20854f25d0db8cdb58ed55d5f0"

        def install
          bin.install "atlan"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/atlanhq/atlan-cli-releases/releases/download/0.1.3-alpha/atlan_Linux_arm64.tar.gz"
        sha256 "80fe5aebc0eabf504157b790b21729ffbf19df5be76c627347e8e8dcf20bf3d2"

        def install
          bin.install "atlan"
        end
      end
    end
  end

  def post_install
    system "#{bin}/atlan"
  end
end
