# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class AtlanAT011 < Formula
    desc "Atlan CLI"
    homepage "https://developer.atlan.com/sdks/cli"
    version "0.1.1"
    license "Apache-2.0"
  
    on_macos do
      on_intel do
        url "https://github.com/atlanhq/atlan-cli-releases/releases/download/v0.1.1/atlan_Darwin_amd64.tar.gz"
        sha256 "c74c8d309f3814e9449ed0cd3f86d20b7381c46403d7adb354c68eeb26553067"
  
        def install
          bin.install "atlan"
        end
      end
      on_arm do
        url "https://github.com/atlanhq/atlan-cli-releases/releases/download/v0.1.1/atlan_Darwin_arm64.tar.gz"
        sha256 "47d5630de2d0f9bf558cba224df7f176b404e3f2190134235d18013ef3618b38"
  
        def install
          bin.install "atlan"
        end
      end
    end
  
    on_linux do
      on_intel do
        if Hardware::CPU.is_64_bit?
          url "https://github.com/atlanhq/atlan-cli-releases/releases/download/v0.1.1/atlan_Linux_amd64.tar.gz"
          sha256 "dce0eb89298a187ddb04abd4c2e90f44c9b191b2eda756d0fc583c636a2c9214"
  
          def install
            bin.install "atlan"
          end
        end
      end
      on_arm do
        if Hardware::CPU.is_64_bit?
          url "https://github.com/atlanhq/atlan-cli-releases/releases/download/v0.1.1/atlan_Linux_arm64.tar.gz"
          sha256 "b6d332d3a017c14270a58e3984a9556e9166252da989657f3eb5f013805b890e"
  
          def install
            bin.install "atlan"
          end
        end
      end
    end
  
    def post_install
      system "#{bin}/atlan"
    end
  end