# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class AtlanAT010 < Formula
    desc "Atlan CLI"
    homepage "https://developer.atlan.com/sdks/cli"
    version "0.1.0"
    license "Apache-2.0"
  
    on_macos do
      on_intel do
        url "https://github.com/atlanhq/atlan-cli-releases/releases/download/v0.1.0/atlan_Darwin_amd64.tar.gz"
        sha256 "dfa3e2fea391f84f2872ed08b54e41859acf8dc3313a3984a583dc0044571abf"
  
        def install
          bin.install "atlan"
        end
      end
      on_arm do
        url "https://github.com/atlanhq/atlan-cli-releases/releases/download/v0.1.0/atlan_Darwin_arm64.tar.gz"
        sha256 "b87e6888281b9c5d87d2f17cd9de00158f40bf76b33f550dec602de3d357fddf"
  
        def install
          bin.install "atlan"
        end
      end
    end
  
    on_linux do
      on_intel do
        if Hardware::CPU.is_64_bit?
          url "https://github.com/atlanhq/atlan-cli-releases/releases/download/v0.1.0/atlan_Linux_amd64.tar.gz"
          sha256 "5c52cd5fa58dc6d20047fecb3895836d70c85a678785b1feaca00e62f2b46ec9"
  
          def install
            bin.install "atlan"
          end
        end
      end
      on_arm do
        if Hardware::CPU.is_64_bit?
          url "https://github.com/atlanhq/atlan-cli-releases/releases/download/v0.1.0/atlan_Linux_arm64.tar.gz"
          sha256 "788138a223b6e4dcf1fa8dfdba18fc71420b1029f7da018f2a72d8770c1cf905"
  
          def install
            bin.install "atlan"
          end
        end
      end
    end
  
    def post_install
      system "#{bin}/atlan"
    end
  end