# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Atlan < Formula
  desc "Atlan CLI"
  homepage "https://developer.atlan.com/sdks/cli"
  version "0.1.13"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/atlanhq/atlan-cli-releases/releases/download/v0.1.13/atlan_Darwin_amd64.tar.gz"
      sha256 "6312102130fc4f92e4cf51efc7df0259904fb1a3c09e9c13d4fa3ccc30b59129"

      define_method(:install) do
        bin.install "atlan"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/atlanhq/atlan-cli-releases/releases/download/v0.1.13/atlan_Darwin_arm64.tar.gz"
      sha256 "2ab84bc9a1b6ee6742b85f7bac2feeb30d04620b1b6cf05db9e32f12ce69f6af"

      define_method(:install) do
        bin.install "atlan"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/atlanhq/atlan-cli-releases/releases/download/v0.1.13/atlan_Linux_amd64.tar.gz"
      sha256 "1aaa7ab76a3f32191d9c1a310964754f9a84c91d874c84a751293295b9e93e17"
      define_method(:install) do
        bin.install "atlan"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/atlanhq/atlan-cli-releases/releases/download/v0.1.13/atlan_Linux_arm64.tar.gz"
      sha256 "5f551babfe590d6ff72e4f9881993c5181c397c0519b91e2619c66485ad55c0f"
      define_method(:install) do
        bin.install "atlan"
      end
    end
  end

  def post_install
    system "#{bin}/atlan"
  end
end
