# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Atlan < Formula
  desc "Atlan CLI"
  homepage "https://developer.atlan.com/sdks/cli"
  version "0.1.10"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/atlanhq/atlan-cli-releases/releases/download/v0.1.10/atlan_Darwin_amd64.tar.gz"
      sha256 "fd9e7f1c3d22e2a9f3ed484454ca2b5cc51e7ae1056ed2c6bbf6ad9fa51938e8"

      def install
        bin.install "atlan"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/atlanhq/atlan-cli-releases/releases/download/v0.1.10/atlan_Darwin_arm64.tar.gz"
      sha256 "bdf6a1ab045aec362e83f855618c83350082eb5f07bd1308a62b93df4bcac08a"

      def install
        bin.install "atlan"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/atlanhq/atlan-cli-releases/releases/download/v0.1.10/atlan_Linux_amd64.tar.gz"
      sha256 "78e46d4d2ab6a6ccfbc56c51eaa84acb58047caef269f5bf8b0249ee9f3b17a0"
      def install
        bin.install "atlan"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/atlanhq/atlan-cli-releases/releases/download/v0.1.10/atlan_Linux_arm64.tar.gz"
      sha256 "bfcbbff132ef2e27ce98c0b7528ff05b30e84888aab89dd9f42253e2c572c4c2"
      def install
        bin.install "atlan"
      end
    end
  end

  def post_install
    system "#{bin}/atlan"
  end
end
