# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class AtlanAT040 < Formula
  desc "Atlan CLI"
  homepage "https://developer.atlan.com/sdks/cli"
  version "0.4.0"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/atlanhq/atlan-cli-releases/releases/download/v0.4.0/atlan_Darwin_amd64.tar.gz"
      sha256 "7960caeaf1c7557b1a6de8fdf4d07367e62acb4777de4e72bcf536320840ea2e"

      define_method(:install) do
        bin.install "atlan"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/atlanhq/atlan-cli-releases/releases/download/v0.4.0/atlan_Darwin_arm64.tar.gz"
      sha256 "f418292c221f368db44d3c21d4b40d994fb03c428413b3cd7bba941aa3bd7092"

      define_method(:install) do
        bin.install "atlan"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/atlanhq/atlan-cli-releases/releases/download/v0.4.0/atlan_Linux_amd64.tar.gz"
      sha256 "efb911cad2cfe822cb8f842c99e9151d0ca15c153838930a6b4a04f327d07e9f"
      define_method(:install) do
        bin.install "atlan"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/atlanhq/atlan-cli-releases/releases/download/v0.4.0/atlan_Linux_arm64.tar.gz"
      sha256 "83bc6bb0f417df7cbfa6c1a7b355f9cf82124a860b90db8527baae12791e145e"
      define_method(:install) do
        bin.install "atlan"
      end
    end
  end

  def post_install
    system "#{bin}/atlan"
  end
end
