# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class AtlanAT050 < Formula
  desc "Atlan CLI"
  homepage "https://developer.atlan.com/sdks/cli"
  version "0.5.0"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/atlanhq/atlan-cli-releases/releases/download/v0.5.0/atlan_Darwin_amd64.tar.gz"
      sha256 "d5e09ebecfcee45d7085e84c904cfe46a724911080a15168ad9aba1a79891a57"

      define_method(:install) do
        bin.install "atlan"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/atlanhq/atlan-cli-releases/releases/download/v0.5.0/atlan_Darwin_arm64.tar.gz"
      sha256 "b00156c6e625de5d59f2233fe18e20bbda835f54860b926b228a8470ba293d6c"

      define_method(:install) do
        bin.install "atlan"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/atlanhq/atlan-cli-releases/releases/download/v0.5.0/atlan_Linux_amd64.tar.gz"
      sha256 "2ae186b214abbded58baf56905b08e4ac6aa11e3bb6f151078c880b16e1ed65c"
      define_method(:install) do
        bin.install "atlan"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/atlanhq/atlan-cli-releases/releases/download/v0.5.0/atlan_Linux_arm64.tar.gz"
      sha256 "2de2d0a67811bc8fea79b2e539afc515e5ba0e56e23b34738b081dbab4961de2"
      define_method(:install) do
        bin.install "atlan"
      end
    end
  end

  def post_install
    system "#{bin}/atlan"
  end
end
